service: Hotel-Miranda-API
plugins:
  - serverless-dotenv-plugin
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
    - "data/**"
    - "public/**"
provider:
  name: aws
  region: eu-west-3
  runtime: nodejs20.x
functions:
  app:
    handler: dist/src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true